name: NightVisionPlus
version: '${project.version}'
main: me.zombieman.nightvisionplus.NightVisionPlus
api-version: 1.13
author: ZombieMan33
authors: [ GoldMember33 ]
commands:
  night-vision:
    aliases:
      - nv
  nightvisionplus:
    aliases:
      - nvp
  night-vision-toggle:
    aliases:
      - nvt
      - nvisiontoggle