name: NightVisionPlus
version: '${project.version}'
main: me.zombieman.nightvisionplus.NightVisionPlus
api-version: 1.13
commands:
  night-vision:
    aliases:
      - nv
  nightvisionplus:
    aliases:
      - nvp