enableMessage: '&aYou enabled night vision'
disableMessage: '&cYou disabled night vision'

toggledMessage: '&aYou toggled night vision to&r %status%&a!'
toggleErrorMessage: '&cInvalid argument. Please use true or false.'

nightVisionEnabled: '&6Enabled'
nightVisionDisabled: '&4Disabled'

enableMessageOthers: '&aYou enabled night vision for: %target-player%'
disableMessageOthers: '&cYou disabled night vision for: %target-player%'

enableMessageToOther: '&a%player% gave you enabled night vision'
disableMessageToOther: '&c%player% removed your night vision'
