name: NightVisionPlus
version: '2.1.1'
main: me.zombieman.nightvisionplus.NightVisionPlus
api-version: 1.13
commands:
  night-vision:
    aliases:
      - nv
  nightvisionplus:
    aliases:
      - nvp